spring.application.name=dat-sach-pj-admin_btvn

server.port=2204
server.servlet.context-path=/admin

spring.datasource.url=jdbc:sqlserver://BTYLAP:1433;databaseName=QlSach_BTVN;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.physical_naming_strategy = org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.web.error.include-message=always
spring.web.error.include-stacktrace=always

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

server.tomcat.max-part-count=100

image.book.location=D:/hoctap/JavaNangCao/projects/dat-sach-pj-admin_btvn/image_sach/